print("HEllo! welcome to this health about program we give information about diseases")
print("1 : covid 19")
print("2 : ebola")
print("3 : Alzheimer")
print("4 : Influenza")
print("5 : Cancer")
print("6 : Dementia")
print("7 : Pneumonia")
print("8 : Meningitis")
input1 = int(input("Alright those are horrible diseases in the list now pick one : "))

if input1 == 1:
    print("covid 19 its in the family of Coronaviridae:")
    print("Coronaviridae is a family enveloped, positive strand RNA viruses which infect amphibians, birds and mammals")
    print("Covid 19 have alot of mutations variants more than 1 thousand but weaker and there is more powerfull mutations example:")
    print("Alpha,Beta,Delta,Gamma")
    print("Covid 19's symptomps:")
    print("common : fever,dry cough,tiredness")
    print("Less common : aches,pains,sore throat,diarrhoea,conjuctivits,headache,loss of taste and smell,rash on skin")
    print("Serious : difficulty breathing,chest pain,loss of speech or movement")
    print("on average it takes 5-6 days from someone is infected with the symptom to show")
    print("how to handle it: self care and if serious symptom must go to the hospital")
    print("how to avoid it: increase your immunity and do protocols goverment has provided")
elif input1 == 2:
    print("Ebola its from family Filoviridae")
    print("Ebola is a popular disease they spread easily")
    print("Ebola's symptoms: ")
    print("fever,headache,muscle pain and chills,internal bleeding,vomiting,coughing blood")
    print("medication for people who gets ebola : blood transfusion and paliative care")
    print("wash your hand,dont handle remain,avoid area known outbreak,avoid bush meat,avoid contact with infected people")
elif input1 == 3:
    print("Alzheimer its family name are apolipoprotein(APOE)")
    print("Alzheimer is a popular disease too")
    print("Alzheimer's symptomps:")
    print("mental decline,depression,hallicunation,appetite loss,etc")
    print("medication : no cure exist but some medication and management strategies may temporarily improve")
    print("How to avoid alzheimer:")
    print("stop smoking,keeping alcohol to minimum,eat healthy,exercise at least 150 minutes evey week")
elif input1 == 4:
    print("Influenza the most common disease")
    print("Influenza,s family name are Orthomyxovirida")
    print("how to avoid influenza:")
    print("avoid close contact with someone who is infected,Stya home when sick,cover your mouth and nose,practice good habits")
    print("lifestyle drug like bed rest and throat lozenge")
elif input1 == 5:
    print("Cancer a horrible disease")
    print("basically cancer is just a over mutation cell")
    print("Cancer symptoms:")
    print("weight loss,fatigue,eating problems,swelling or lumps")
    print("how to cure cancer :")
    print("Surgery,Chemotherapy,Radiation therapy,Bone marrow transplant,Hormone therapy,targeted drug therapy,Cryoablation")
    print("How to avoid cancer:")
    print("dont use tobacco,eat healthy diet,mantain healthy weight and physically active,protect yourself from the sun,get vaccinated,avoid risky behaviour,regular medical care")
elif input1 == 6:
    print("Dementia is a horrible disease too")
    print("Dementia includes full of forgetness")
    print("Dementia's symptoms:")
    print("Cognitive,Behavioural,Mood,Pyshcological,Muscular,etc")
    print("How to cure dementia:")
    print("therapy and medications")
    print("how to avoid dementia:")
    print("eat healthy,dont smoke,drink less alcohol,exercise your mind,take control of your health,be physically active")
elif input1 == 7:
    print("Pneumonia is a mid horrible disease")
    print("Pneumonia's symptoms:")
    print("Sharp in chest,fever,chills,dehydration,fatigue,loss of appettite,mlaise,clammy skin,fast breathing,shallow breathing,cough")
    print("How to cure pneumonia : ")
    print("Antibiotic,Penicillin,Oxygen therapy,etc")
    print("how to avoid pneumonia:")
    print("get flu vaccine every year,dont smoke,practive good hygiene,get pneumococcal vaccine,avoid sick people,practice good lifestyle")
elif input1 == 8:
    print("Meningitis mid horrible disease")
    print("Meningitis's symptoms:")
    print("fever,chills,fatigue,lethargy,confusion,fast heart rate,nausea,etc")
    print("how to cure meningitis:")
    print("antibiotic,steroid,penicillin,oxygen therapy and hospitalisation")
    print("how to avoid meningitis:")
    print("WASH YOUR HAND,practice good hygiene,stay healthy,cover your mouth")
else:
    print("please read the list again")
print("")
print("")
print("")
print("")
print("")
d1 = int(input("Okay time to diagnose you enter your symptoms [1 : sneezing | 2 : sore throat ]: "))
d2 = int(input("Alright pick again { 1 : coughing | 2 : wheezing voice] : "))
if d1 + d2 == 2 :
    print("ok probably either its flu or something more bad and if something more bad go to the doctor and take a test if its a flu dont worry drink a medicine")
elif d1 + d2 == 4:
    print("it seems you got laryingitis dont worry its not a horrible disease you could just eat a throat lozenge and rest your voice dont talk too much in conclusion")
else:
    print("ehhh try again")
        

          
          
